[project]
name = "dev_utils"
version = "0.0.1"
dynamic = ["dependencies"]

[project.scripts]
config = "dev_utils.src.config:print_envs"
main = "dev_utils.src.main:main"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
