[project]
name = "dev_utils"
version = "0.0.4"
dynamic = ["dependencies"]

[project.scripts]
#config = "dev_utils.src.config:print_envs"
#main = "dev_utils.src.main:main"
bump-ver = "dev_utils.src.utils.version:app"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
